### ISSUE TITLE
Update Interval 

### ISSUE THREAD

**Issue by bkabela** [Red5d/ha-gasbuddy#6]
I'm not sure if this project is still active or not but was wondering if you could add the ability to pull new prices every few hours or so? As of right now it only updates when HA is restarted. Thanks!

**Comment by Red5d** [comment]
Are you sure it's only updating on restart, or is the price data on gasbuddy for your station(s) not being updated frequently? The integration should check for updates every hour or so. I just checked and I have one gas station on my Home Assistant that last updated 4 hours ago, one 22 hours ago, and one last week.
