### ISSUE TITLE
No entity has been created

### ISSUE THREAD

**Issue by muhepd** [Red5d/ha-gasbuddy#7]
Hi, thank you for your time in building this repo, however I am having issues.

I followed the instructions, added and installed the custom repository in HACS, rebooted Home Assistant, then configured the config yaml file as per the instructions, I added the station id, rebooted Home Assistant again, but I go to see if the entity is there, and it isn't... 

Does it matter if I am in Canada and I am using a Canadian gas station id? When I went to gasbuddy website it asked me if I was in USA or Canada.

Thanks.

**Comment by Red5d** [comment]
Are there any errors from this integration on the Home Assistant logs page? If the Canadian GasBuddy site uses a different URL for retrieving gas station data, it might not work correctly for you currently.

This is the line/URL that I'm currently using:

(sensor.py, line 27)

    r = requests.post("https://www.gasbuddy.com/gaspricemap/station", data={'id': config[CONF_STATIONID], 'fuelTypeId': '1'})

**Comment by muhepd** [comment]
Hi Thank you replying. I fixed it, it was something on my end. The Canadian URL is that same as the one you are using.
